// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiPYfyutdu6zHp9CXOAFRLf4Vwpw8k32Q',
    appId: '1:572279031586:web:30ed8a658c62374bb2477b',
    messagingSenderId: '572279031586',
    projectId: 'leopay-2805b',
    authDomain: 'leopay-2805b.firebaseapp.com',
    storageBucket: 'leopay-2805b.firebasestorage.app',
    measurementId: 'G-ZQGC75NXF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-acO7DcwDxOWKUDyEV3PStSOTqqkUwxk',
    appId: '1:572279031586:android:83950eff7f8bfea4b2477b',
    messagingSenderId: '572279031586',
    projectId: 'leopay-2805b',
    storageBucket: 'leopay-2805b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS4WP3h149NaieCqdmTXnrcpnlbQ6vAmU',
    appId: '1:572279031586:ios:9a9cdb3e03a7b32cb2477b',
    messagingSenderId: '572279031586',
    projectId: 'leopay-2805b',
    storageBucket: 'leopay-2805b.firebasestorage.app',
    iosBundleId: 'com.example.leopay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS4WP3h149NaieCqdmTXnrcpnlbQ6vAmU',
    appId: '1:572279031586:ios:9a9cdb3e03a7b32cb2477b',
    messagingSenderId: '572279031586',
    projectId: 'leopay-2805b',
    storageBucket: 'leopay-2805b.firebasestorage.app',
    iosBundleId: 'com.example.leopay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiPYfyutdu6zHp9CXOAFRLf4Vwpw8k32Q',
    appId: '1:572279031586:web:47bcf88341c11214b2477b',
    messagingSenderId: '572279031586',
    projectId: 'leopay-2805b',
    authDomain: 'leopay-2805b.firebaseapp.com',
    storageBucket: 'leopay-2805b.firebasestorage.app',
    measurementId: 'G-5FPQGCNPQN',
  );
}
